// Builds vendor/pink-trombone.js from the workspace shelf's copy of Pink
// Trombone, which is a whole web page. Only its sound is wanted: the Glottis
// object, the Tract object, and the noise routine they call. This script cuts
// those three spans out of the page unchanged and wraps them as a module.
//
//   node scripts/vendor_pink_trombone.mjs          writes the file
//   node scripts/vendor_pink_trombone.mjs --print  prints it and writes nothing
//
// scripts/check_creatures.mjs calls build() and compares, so the vendored file
// is always exactly what this script makes from the shelf copy.

import fs from 'node:fs';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const here = name => fileURLToPath(new URL(name, import.meta.url));
export const SHELF = here('../../../third-party/pink-trombone/index.html');
export const OUT = here('../vendor/pink-trombone.js');

// The text from the line matching `from` up to, not including, the line
// matching `to`.
function span(page, from, to) {
  const a = page.search(from), rest = page.slice(a), b = rest.search(to);
  if (a < 0 || b < 0) throw new Error(`span not found: ${from} to ${to}`);
  return rest.slice(0, b);
}

export function build(source = fs.readFileSync(SHELF)) {
  const sha = crypto.createHash('sha256').update(source).digest('hex');
  const page = source.toString('utf8').replace(/^﻿/, '').replace(/\r\n/g, '\n');

  // The author's notice, from the comment that opens the page.
  const notice = span(page, /^P I N K   T R O M B O N E$/m, /^-->$/m).trimEnd();
  // The page is not strict code and writes one zero as `00`, an octal literal a
  // module refuses. That token is the one change made inside a copied span.
  const octal = 'keyboardLeft : 00,';
  const original = span(page, /^var Glottis =\s*$/m, /^var Tract =\s*$/m).trimEnd();
  if (!original.includes(octal)) throw new Error('the octal literal is not where it was');
  const glottis = original.replace(octal, 'keyboardLeft : 0,');
  const tract = span(page, /^var Tract =\s*$/m, /^var TractUI =\s*$/m).trimEnd();
  const start = page.lastIndexOf('/*', page.indexOf(' * A speed-improved perlin'));
  const tail = '})(this);';
  const end = page.indexOf(tail, start);
  if (start < 0 || end < 0) throw new Error('noise routine not found');
  const noise = page.slice(start, end);

  return `// VENDORED AND MODIFIED COPY. Do not edit by hand: it is generated by
// scripts/vendor_pink_trombone.mjs, and scripts/check_creatures.mjs fails if
// it differs from what that script makes.
//
// Source: https://dood.al/pinktrombone/ (Pink Trombone 1.1), taken from the
// workspace shelf, third-party/pink-trombone/index.html.
// Source SHA-256: ${sha}
//
// What was changed. The source is one web page. Three spans of its script are
// copied here: the Glottis object, the Tract object, and the noise routine.
// They are unchanged except for one token in Glottis, \`keyboardLeft : 00\`,
// written here as \`0\` because a module refuses the octal literal. Everything else on the page (drawing, touch handling, and the
// audio node set-up) is left out. Added around the spans: the declarations
// just below, which stand in for globals the page defined; the last line of
// the noise routine, which attached it to the window and here attaches it to a
// local object; and the exports at the end.
//
// The author's notice, which covers the spans below:
//
/*
${notice}
*/
//
// The noise routine carries its own notice, further down, placing it in the
// public domain.

// The page added clamp and moveTowards to the global Math. Here they are on a
// local Math that inherits the real one, so nothing global is changed.
const Math = Object.assign(Object.create(globalThis.Math), {
  clamp(number, min, max) { return number < min ? min : number > max ? max : number; },
  moveTowards(current, target, amountUp, amountDown) {
    return current < target ? globalThis.Math.min(current + amountUp, target) : globalThis.Math.max(current - amountDown, target);
  },
});

// Globals the page defined. \`output\` is assigned without a declaration in
// Glottis.normalizedLFWaveform, which a module does not allow.
let sampleRate = 44100, alwaysVoice = false, autoWobble = false, output;
const UI = { touchesWithMouse: [] };
// The page's two drawing canvases. Glottis keeps a reference to one; nothing
// here calls the functions that draw.
const backCtx = null, tractCtx = null;
const AudioSystem = { blockLength: 512, blockTime: 512 / 44100 };
const __global = {};

// ---- copied span: noise routine ---------------------------------------------
${noise}})(__global);
const noise = __global.noise;

// ---- copied span: Glottis ---------------------------------------------------
${glottis}

// ---- copied span: Tract -----------------------------------------------------
${tract}

// ---- added: exports ---------------------------------------------------------
export { Glottis, Tract, noise, AudioSystem };
export function setSampleRate(rate) { sampleRate = rate; AudioSystem.blockTime = AudioSystem.blockLength / rate; }
export function setAlwaysVoice(on) { alwaysVoice = on; }
export function setAutoWobble(on) { autoWobble = on; }
`.replace(/\r\n/g, '\n');   // the same output whatever line endings this script was checked out with
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const made = build();
  if (process.argv.includes('--print')) process.stdout.write(made);
  else { fs.writeFileSync(OUT, made); console.log(`wrote ${OUT} (${made.length} characters)`); }
}
